export const ADD_EXPENSE = "ADD_EXPENSE";
export const ADD_EXPENSES = "ADD_EXPENSES";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const SET_BUDGET = "SET_BUDGET";
export const ADD_REMAINING = "ADD_REMAINING";
export const ADD_TOTAL_EXPENSE = "ADD_TOTAL_EXPENSE";
